import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';
import { withAuth } from '@/lib/security';
import { assertQuota, recordAiAction } from '@/lib/billing/metering';

const apiKey = process.env.AI_API_KEY;
const openai = apiKey ? new OpenAI({ apiKey }) : null;
const tavilyApiKey = process.env.TAVILY_API_KEY;

async function tavilySearch(query: string) {
    if (!tavilyApiKey) return [];
    try {
        const response = await fetch('https://api.tavily.com/search', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                api_key: tavilyApiKey,
                query,
                search_depth: 'basic',
                include_answer: false,
                max_results: 5,
            }),
        });
        const data = await response.json();
        return data.results || [];
    } catch (error) {
        console.error('Tavily search failed:', error);
        return [];
    }
}

async function handler(req: NextRequest, { userId }: { userId: string }) {
    if (!openai) {
        return NextResponse.json({ error: 'AI API Key missing' }, { status: 500 });
    }

    try {
        try {
            await assertQuota(userId);
        } catch (e: any) {
            if (e.code === 'quota_reached') {
                return NextResponse.json({ code: 'quota_reached', error: 'AI actions limit reached for this month.' }, { status: 403 });
            }
            throw e;
        }

        const { competitors, existingSignalTitles = [], language = 'fr' } = await req.json();

        if (!competitors?.length) {
            return NextResponse.json({ signals: [] });
        }

        // Search for each competitor (limit to 5)
        const allResults: { competitor: string; competitorId: string; results: any[] }[] = [];
        for (const comp of competitors.slice(0, 5)) {
            const results = await tavilySearch(
                `"${comp.name}" news update ${new Date().getFullYear()}`
            );
            if (results.length > 0) {
                allResults.push({
                    competitor: comp.name,
                    competitorId: comp.id,
                    results,
                });
            }
        }

        if (allResults.length === 0) {
            return NextResponse.json({ signals: [] });
        }

        const lang = language === 'fr' ? 'French' : 'English';

        const systemPrompt = `You are a market intelligence analyst. Classify the following news articles about competitors into structured market signals.

For each relevant article, create a market signal object. SKIP articles that are:
- Not relevant to the competitive landscape
- Duplicates of existing signals (titles provided below)
- Too generic or not actionable

Output MUST be a valid JSON object:
{
    "signals": [
        {
            "title": string (concise title in ${lang}),
            "description": string (1-2 sentence summary in ${lang}),
            "source": string (source name),
            "sourceUrl": string (URL),
            "impact": "positive" | "negative" | "neutral" (impact on OUR business),
            "category": "funding" | "product_launch" | "pricing_change" | "partnership" | "hiring" | "acquisition" | "market_entry" | "regulation" | "technology" | "leadership" | "other",
            "urgency": "low" | "medium" | "high" | "critical",
            "competitorName": string,
            "competitorId": string,
            "aiSummary": string (brief AI-generated insight about what this means for us)
        }
    ]
}

Maximum 3 signals per competitor, maximum 10 total.`;

        const userPrompt = `EXISTING SIGNAL TITLES (skip duplicates):
${existingSignalTitles.join('\n')}

NEWS ARTICLES BY COMPETITOR:
${JSON.stringify(allResults, null, 2)}`;

        const response = await openai.chat.completions.create({
            model: 'gpt-4o',
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userPrompt },
            ],
            response_format: { type: 'json_object' },
            temperature: 0.3,
        });
        await recordAiAction(userId, 'api', response.usage?.total_tokens || 0, 'gpt-4o').catch(console.error);

        const content = response.choices[0].message.content;
        const result = JSON.parse(content || '{"signals": []}');

        // Add metadata
        const signals = (result.signals || []).map((signal: any) => ({
            ...signal,
            date: new Date().toISOString().split('T')[0],
            isAutoGenerated: true,
        }));

        return NextResponse.json({ signals });
    } catch (error) {
        console.error('Market Scan Error:', error);
        return NextResponse.json(
            { error: 'Failed to scan market' },
            { status: 500 }
        );
    }
}

export const POST = withAuth(handler);
